-- Conectar como administrador
-- sqlplus / as sysdba

-- Crear el usuario
CREATE USER INMOBILIARIA IDENTIFIED BY inmobiliaria123;

-- Otorgar privilegios necesarios
GRANT CREATE SESSION TO INMOBILIARIA;
GRANT CREATE TABLE TO INMOBILIARIA;
GRANT CREATE SEQUENCE TO INMOBILIARIA;
GRANT CREATE TRIGGER TO INMOBILIARIA;
GRANT CREATE PROCEDURE TO INMOBILIARIA;
GRANT CREATE VIEW TO INMOBILIARIA;

-- Otorgar espacio de tablespace
ALTER USER INMOBILIARIA QUOTA UNLIMITED ON USERS;

-- Otorgar privilegios adicionales necesarios para JPA
GRANT CREATE ANY INDEX TO INMOBILIARIA;
GRANT ALTER ANY TABLE TO INMOBILIARIA;
GRANT DROP ANY TABLE TO INMOBILIARIA;
